### ISSUE TITLE
Heating function not implemented

### ISSUE THREAD

**Issue by phcollignon** [laurent-martin/ets-to-homeassistant#21]
Hello, 

I get this message for heating functions :  
```
WARN -- : Bath room Radiator function type heating_radiator not implemented
WARN -- : Radiator Bath room heating_radiator: function type not detected, skipping
WARN -- : Bath room Floor function type heating_floor not implemented
WARN -- : Floor Bath room heating_floor: function type not detected, skipping
```
And nothing converted to HA.   Is it not implemented yet in the ruby lib ? neither in the source code ?

Regards,

**Comment by phcollignon** [comment]
I've just checked in the code, indeed it's not implemented  ...
[https://github.com/laurent-martin/ets-to-homeassistant/blob/f4e2413b502751e9c757bd778bc372fcbc430574/lib/ets_to_hass/generator.rb#L207](https://github.com/laurent-martin/ets-to-homeassistant/blob/f4e2413b502751e9c757bd778bc372fcbc430574/lib/ets_to_hass/generator.rb#L207)

**Comment by laurent-martin** [comment]
If you have a proposal for mapping, feel free to propose.

**Comment by phcollignon** [comment]
There is a sensors map here : https://www.home-assistant.io/integrations/knx/#value-types
Other devices are defined on that page, binary_sensor i.e could be mapped to dpt 1.002 or 1.009

**Comment by Superwallah** [comment]
If DPT is 20.102, then this device should be mapped to domain "climate" and attribute "hvac_mode" (...though this DPT is often also used for the HVAC mode status object). 
All other addresses may be listed under a commented line like
`# to_be_mapped: 1/2/3`

Alternatively, multiple options may be and in the same line, but as a comment:
`# temperature_address | target_temperature_address: 1/2/3  # delete the wrong attributes!`

**Comment by TheFelix93** [comment]
This how I implemented climate in my fork of this script: https://github.com/TheFelix93/ets-to-homeassistant

```
climate:
    - name: "Wohnen"
      temperature_address: "4/1/1"
      target_temperature_state_address: "4/1/2"  #current setpoint
      setpoint_shift_address: "4/1/2"   #setpoint comfort
      setpoint_shift_state_address: "4/1/4"
      setpoint_shift_mode: "DPT9002"
      temperature_step: 0.5
      operation_mode_address: "4/1/8"   #Betriebsmodus
      operation_mode_state_address: "4/1/9"  #Status Betriebsmodus
      min_temp: 18
      max_temp: 26
```
